spring:
  application:
    name: biz

---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/base_app
    username: root
    password: tutq@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# ---
# spring:
#   jackson:
#     serialization:
#       write-dates-as-timestamps: false
---
log:
  app_name: base-app
  pattern: "[%p] %d{yy-MM-dd HH:mm:ss.SSS, GMT+7:00} %C{5}.%M.%L: %m%n"
  logstash:
    destination: 10.100.20.99:5000
  file:
    path: "/opt/logs"
---
logging:
  level:
    com:
      zaxxer: ERROR
    org:
      apache: ERROR
      hibernate: ERROR
      springframework: ERROR
