---
spring:
  datasource:
    url: jdbc:mysql://10.0.70.4:3306/base_app
    username: root
    password: tutq@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

---
management:
  endpoints:
    web:
      exposure:
        include: "*"

---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}